### ISSUE TITLE
determining cause of 'amixer set PCM 5%-' returning "invalid command"

### ISSUE THREAD

**Issue by smokytheangel0** [bear24rw/alsa-utils#1]
So I'm just looking for a little direction here:

I have a raspberry pi zero w, using an adafruit mono i2s amp installed with the hifiberry i2s dac script, and some GPIO buttons set to trigger the commands ["amixer set PCM 5%-", "amixer set PCM 5%+"]. This works fine 60% of the time, however occaisionally when I start the pi it becomes stuck at full volume. Amixer begins to output "invalid command" instead of the normal status lines when given the very same input, and the alsamixer tui does not change volume either, the device shows up as PCM but the up and down buttons dont affect the volume level.

I looked in alsamixer.c and it looks like this output of 'invalid command' is caused by either sset_enum() or sset_channels() returning a negative integer, apparently meaning that check_flag within them is failing to be set, because none of the branches are being entered when these functions are run. I am new to programming and extremely new to reading other's code so I am getting a bit lost when tracking down the conditions that would cause this error. If you could help me understand what conditions are not being met when this error appears, that would help me alot.

**Comment by bear24rw** [comment]
Hi, this is a super old fork that I only made to enable background transparency. You might want to try asking either on the alsa mailing list or one of the linux reddits.

**Comment by smokytheangel0** [comment]
thank you

**Comment by sir66** [comment]
I have this problem now with Raspberry Pi Zero W with Adafruit Speaker Bonnet for Raspberry Pi.

root@raspberrypi-zw:/home/pi# amixer -c 0 set PCM 255
Simple mixer control 'PCM',0
  Capabilities: volume
  Playback channels: Front Left - Front Right
  Capture channels: Front Left - Front Right
  Limits: 0 - 255
  Front Left: 255 [100%]
  Front Right: 255 [100%]
root@raspberrypi-zw:/home/pi# amixer -c 0 set PCM 254
amixer: Invalid command!
root@raspberrypi-zw:/home/pi#

Тhe problem occurs from time to time. After reboot all work fine. Did you find some decision or workaround?

**Comment by sir66** [comment]
> So I'm just looking for a little direction here:
> 
> I have a raspberry pi zero w, using an adafruit mono i2s amp installed with the hifiberry i2s dac script, and some GPIO buttons set to trigger the commands ["amixer set PCM 5%-", "amixer set PCM 5%+"]. This works fine 60% of the time, however occaisionally when I start the pi it becomes stuck at full volume. Amixer begins to output "invalid command" instead of the normal status lines when given the very same input, and the alsamixer tui does not change volume either, the device shows up as PCM but the up and down buttons dont affect the volume level.
> 
> I looked in alsamixer.c and it looks like this output of 'invalid command' is caused by either sset_enum() or sset_channels() returning a negative integer, apparently meaning that check_flag within them is failing to be set, because none of the branches are being entered when these functions are run. I am new to programming and extremely new to reading other's code so I am getting a bit lost when tracking down the conditions that would cause this error. If you could help me understand what conditions are not being met when this error appears, that would help me alot.

I have this problem now with Raspberry Pi Zero W with Adafruit Speaker Bonnet for Raspberry Pi.

root@raspberrypi-zw:/home/pi# amixer -c 0 set PCM 255
Simple mixer control 'PCM',0
Capabilities: volume
Playback channels: Front Left - Front Right
Capture channels: Front Left - Front Right
Limits: 0 - 255
Front Left: 255 [100%]
Front Right: 255 [100%]
root@raspberrypi-zw:/home/pi# amixer -c 0 set PCM 254
amixer: Invalid command!
root@raspberrypi-zw:/home/pi#

Тhe problem occurs from time to time. After reboot all work fine. Did you find some decision or workaround?

**Comment by besi** [comment]
Same problem here on a raspberry pi running bookworm and using the Adafruit I2S speaker bonnet. This morning it worked and now it doesn't anymore.

And it seems to persist after a reboot.

I had this before and re-installing using adafruit's script worked but I would prefer to not have to run this over and over again.
